"""add short_links

Revision ID: 301d1b402d95
Revises: b37e28ee3bc6
Create Date: 2026-10-02 16:19:43.496679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '301d1b402d95'
down_revision = 'b37e28ee3bc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('tracking_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tracking_uuid'], ['campaign_targets.tracking_uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_links_code'), 'short_links', ['code'], unique=True)
    op.create_index(op.f('ix_short_links_tracking_uuid'), 'short_links', ['tracking_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_short_links_tracking_uuid'), table_name='short_links')
    op.drop_index(op.f('ix_short_links_code'), table_name='short_links')
    op.drop_table('short_links')
    # ### end Alembic commands ###
