"""add pages.logo_url

Revision ID: fdacc5a0125b
Revises: 6be49942dec9
Create Date: 2026-10-02 16:04:59.592979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdacc5a0125b'
down_revision = '6be49942dec9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('logo_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'logo_url')
    # ### end Alembic commands ###
